package ItemStats;

public class ItemStats_Tema {
	
	Object_ItemStats_Tema[] Temaer;
	
	public ItemStats_Tema() {
		
		Temaer = new Object_ItemStats_Tema[1000];
		InsertStater();
	}
	
	private void InsertStater() {
		//InsertNewStat( "norsk oversettelse", "søkeord", "hovedkategori", "subkategori" );
		InsertNewStat( "t&oslashrker raskt", "fast drying", null, null, null, null );
		InsertNewStat( "moteriktig", "fashion", null, null, null, null );
		InsertNewStat( "leopard", "leopard", null, null, null, null );
		InsertNewStat( "badet&oslashy", "swimwear", "Badet&oslashy", null, null, null );
		InsertNewStat( "badedrakt", "swimsuit", "Badet&oslashy", null, null, null );
		InsertNewStat( "concealer", "concealer", null, null, null, null ); //sminke
		InsertNewStat( "concealer", "hide the blemish", "Sminke", null, null, null ); //sminke
		InsertNewStat( "foundation", "foundation", null, null, null, null ); //sminke, negledesign, miniatyrmaling
		InsertNewStat( "plastikk", "plastic", null, null, null, null );
		InsertNewStat( "skateboarding", "skateboarding", null, null, null, null );
		InsertNewStat( "USA-flagg", "usa flag", null, null, null, null );
		InsertNewStat( "lysende", "luminous", null, null, null, null );
		InsertNewStat( "retro", "retro", null, null, null, null );
		InsertNewStat( "polyester", "polyester", null, null, null, null );
		InsertNewStat( "casual", "casual", null, null, null, null );
		InsertNewStat( "lerretsduk", "canvas", null, null, null, null );
		InsertNewStat( "glidel&arings", "zipper", null, null, null, null );
		InsertNewStat( "glidel&arings", "velcro", null, null, null, null );
		InsertNewStat( "klassisk", "classical", null, null, null, null );
		InsertNewStat( "skinn", "fur", null, null, null, null );
		InsertNewStat( "deksel", "case", null, null, null, null );
		InsertNewStat( "kortholder", "card bag", null, null, null, null );
		InsertNewStat( "selvlysende", "fluorescent", null, null, null, null );
		InsertNewStat( "selvlysende", "glow in the dark", null, null, null, null );
		InsertNewStat( "pedikyr", "pedicure", null, null, null, null );
		InsertNewStat( "akrylfjerner", "acrylic remover", null, null, null, null );
		InsertNewStat( "metallic", "metallic", null, null, null, null );
		InsertNewStat( "skinnende", "shiny", null, null, null, null );
		InsertNewStat( "retter", "corrector", null, null, null, null );
		InsertNewStat( "troll", "troll", null, null, null, null );
		InsertNewStat( "Wallace & Gromit", "wallace and gromit", null, null, null, "cartoonish" );
		InsertNewStat( "kropp", "body", null, null, null, null );
		InsertNewStat( "mobiltelefon", "mobile phone", null, null, null, null );
		InsertNewStat( "skruehull", "screw hole", null, null, null, null );
		InsertNewStat( "bakgrunnsbilde", "wallpaper", null, null, null, null );
		InsertNewStat( "klistremerker", "sticker", null, null, null, null );
		InsertNewStat( "perler", "beaded", null, null, null, null );
		InsertNewStat( "tenking", "thinking", null, null, null, null );
		InsertNewStat( "trening", "exercise", null, null, null, null );
		InsertNewStat( "logikk", "logical", null, null, null, null );
		InsertNewStat( "spill", "game", null, null, null, null );
		InsertNewStat( "svamp", "sponge", null, null, null, null );
		InsertNewStat( "powder", "pulver", null, null, null, null );
		InsertNewStat( "p&aringle", "pole", null, null, null, null );
		InsertNewStat( "pinne", "stick", null, null, null, null );
		InsertNewStat( "iskrem", "ice cream", null, null, null, null );
		InsertNewStat( "stol", "chair", null, null, null, null );
		InsertNewStat( "piano", "piano", null, null, null, "musikk" );
		InsertNewStat( "elektronisk", "electronic", null, null, null, null );
		InsertNewStat( "intellektuell", "intellectual", null, null, null, null );
		InsertNewStat( "multifunktsjonell", "multifunctional", null, null, null, null );
		InsertNewStat( "form", "shape", null, null, null, null );
		InsertNewStat( "vokalisering", "vocalization", null, null, null, null );
		InsertNewStat( "rotering", "rotation", null, null, null, null );
		InsertNewStat( "treklosser", "wooden beads", "Leker", null, null, "leke" );
		InsertNewStat( "myk ball", "soft ball", "Leker", null, null, null );
		InsertNewStat( "hjul", "wheel", null, null, null, null );
		InsertNewStat( "trilleb&aringrlass", "barrowload", null, null, null, null );
		InsertNewStat( "trilleb&aringre", "wheelbarrow", null, null, null, null );
		InsertNewStat( "b&aringre", "barrow", null, null, null, null );
		InsertNewStat( "anime", "anime", null, null, null, "cartoonish" );
		InsertNewStat( "musikk", "music", null, null, null, "lyd" );
		InsertNewStat( "musikalsk", "musical", null, null, null, "lyd" );
		InsertNewStat( "miniatyrfigur", "lilliputian", "Modellfigurer", null, null, null );
		InsertNewStat( "halskjede", "necklace", null, null, null, null );
		InsertNewStat( "armb&aringnd", "bracelet", null, null, null, null );
		InsertNewStat( "kanon", "cannon", null, null, null, "skytev&aringpen" );
		InsertNewStat( "Halloween", "halloween", null, null, null, null );
		InsertNewStat( "romskip", "spaceship", null, null, null, "verdensrommet" );
		InsertNewStat( "Star Trek", "star trek", null, null, null, "filmfigur" );
		InsertNewStat( "Star Trek", "startrek", null, null, null, "filmfigur" );
		InsertNewStat( "kran", "crane", null, null, null, null );
		InsertNewStat( "decals", "decal", null, null, null, null );
		InsertNewStat( "Nemo", "nemo", null, null, null, "filmfigur" );
		InsertNewStat( "verkt&oslashy", "tool", null, null, null, null );
		InsertNewStat( "magnetisk", "magnetic", null, null, null, null );
		InsertNewStat( "v&aringpen", "weapon", null, null, null, null );
		InsertNewStat( "frukt", "fruit", null, null, null, null );
		InsertNewStat( "berg-og-dalbane", "roller coaster", null, null, null, "barn" );
		InsertNewStat( "skyskraper", "skyscraper", null, null, null, null );
		InsertNewStat( "by", "city", null, null, null, null );
		InsertNewStat( "HQ", "hq", null, null, null, null );
		InsertNewStat( "boots", "boots", "Sko", "Boots", null, "sko" );
		InsertNewStat( "baser", "bases", null, null, null, null );
		InsertNewStat( "lord", "lord", null, null, null, null );
		InsertNewStat( "HDMI", "hdmi", null, null, null, null );
		InsertNewStat( "hjerte", "heart", null, null, null, null );
		InsertNewStat( "vinger", "wing", null, null, null, null );
		InsertNewStat( "kors", "cross", null, null, null, "religion" );
		InsertNewStat( "kryssild", "cross fire", null, null, null, "v&aringpen" );
		InsertNewStat( "Vigorous Dragon", "vigorous dragon", null, null, null, null );
		InsertNewStat( "hodeskalle", "skull", null, null, null, "skjelett" );
		InsertNewStat( "krone", "crown", null, null, null, null );
		InsertNewStat( "briller", "glasses", "Briller", null, null, null );
		InsertNewStat( "kirseb&aeligr", "cherry", null, null, null, "frukt" );
		InsertNewStat( "fred", "peace", null, null, null, null );
		InsertNewStat( "bein", "bone", null, null, null, "skjelett" );
		InsertNewStat( "sykkel", "bike", null, null, null, null );
		InsertNewStat( "sykkel", "bicycle", null, null, null, null );
		InsertNewStat( "Super Mario", "super mario", null, null, null, "spillfigur" );
		InsertNewStat( "Angry Birds", "Angry Birds", null, null, null, "spillfigur" );
		InsertNewStat( "Pokemon", "pokemon", null, null, null, "spillfigur" );
		InsertNewStat( "gladiator", "gladiator", null, null, null, "kriger" );
		InsertNewStat( "alv", "elf", null, null, null, "fantasy" );
		InsertNewStat( "Chaos", "Chaos", null, null, null, null );
		InsertNewStat( "skytev&aringpen", "gun", null, null, null, "krig" );
		InsertNewStat( "skytev&aringpen", "handgun", null, null, null, "krig" );
		InsertNewStat( "Hello Kitty", "hello kitty", null, null, null, "cartoonish" );
		InsertNewStat( "robot", "robot", null, null, null, "sci-fi" );
		InsertNewStat( "ninja", "ninja", null, null, null, "Japan" );
		InsertNewStat( "pistol", "pistol", null, null, null, "krig" );
		InsertNewStat( "kryssord", "crossword", null, null, null, null );
		InsertNewStat( "scrabble", "scrabble", null, null, null, null );
		InsertNewStat( "politistasjon", "police station", null, null, null, null );
		InsertNewStat( "politi", "police", null, null, null, null );
		InsertNewStat( "passasjervogn", "passenger car", null, null, null, null );
		InsertNewStat( "maya", "mayan", null, null, null, null );
		InsertNewStat( "koffert", "suitcase", null, null, null, "lugasje" );
		InsertNewStat( "ridder", "knight", null, null, null, "krig" );
		InsertNewStat( "t&aringrn", "Tower", null, null, null, null );
		InsertNewStat( "bro", "bridge", null, null, null, null );
		InsertNewStat( "manekeng", "manikin", null, null, null, null );
		InsertNewStat( "milit&aeligre", "military", null, null, null, "krig" );
		InsertNewStat( "konge", "king", null, null, null, null );
		InsertNewStat( "Prince", "Prince", null, null, null, null );
		InsertNewStat( "base", "base", null, null, null, null );
		InsertNewStat( "astronaut", "astronaut", null, null, null, "verdensrommet" );
		InsertNewStat( "n&oslashkkelring", "key chain", "Diverse", "N&oslashkkelringer", null, null );
		InsertNewStat( "sko", "shoes", null, null, null, null );
		InsertNewStat( "Three Kingdoms", "Three Kingdoms", null, null, null, null );
		InsertNewStat( "motor", "motor", null, null, null, null );
		InsertNewStat( "str&oslashmpebukse", "long john", null, null, null, null );
		InsertNewStat( "skole", "school", null, null, null, "barn" );
		InsertNewStat( "byste", "bust", null, null, null, null );
		InsertNewStat( "romferge", "shuttle", null, null, null, "verdensrommet" );
		InsertNewStat( "superhelt", "superhero", null, null, null, null );
		InsertNewStat( "superhelt", "super hero", null, null, null, null );
		InsertNewStat( "kaptein", "captain", null, null, null, null );
		InsertNewStat( "Legion", "Legion", null, null, null, null );
		InsertNewStat( "magneter", "magnet", null, null, null, null );
		InsertNewStat( "Den Sorte Perle", "the black pearl", null, null, null, null );
		InsertNewStat( "sort perle", "black pearl", null, null, null, null );
		InsertNewStat( "pyramide", "pyramid", null, null, null, "Egypt" );
		InsertNewStat( "kommando", "commando", null, null, null, null );
		InsertNewStat( "Thomas", "thomas", null, null, null, null );
		InsertNewStat( "Sandkunst", "sand art", "Hobby", null, null, "hobby" );
		InsertNewStat( "2003", "2003", null, null, null, null );
		InsertNewStat( "motor", "engine", null, null, null, null );
		InsertNewStat( "deler", "parts", null, null, null, null );
		InsertNewStat( "inngravering", "etching", null, null, null, null );
		InsertNewStat( "avbitertang", "cutter", null, null, null, "verkt&oslashy" );
		InsertNewStat( "displayboks", "display case", null, null, null, null );
		InsertNewStat( "USMC", "usmc", null, null, null, null );
		InsertNewStat( "Howitzer", "howitzer", null, null, null, null );
		InsertNewStat( "radio", "radio", null, null, null, null );
		InsertNewStat( "radio", "radio", null, null, null, null );
		InsertNewStat( "duke", "duke", null, null, null, null );
		InsertNewStat( "Kawasaki", "kawasaki", null, null, null, null );
		InsertNewStat( "transport", "transporter", null, null, null, null );
		InsertNewStat( "perle", "bead", null, null, null, null );
		InsertNewStat( "papirmodell", "paper model", null, null, null, null );
		InsertNewStat( "badet&oringy", "swimwear", null, null, null, null );
		InsertNewStat( "badet&oringy", "bathing suit", null, null, null, null );
		InsertNewStat( "jul", "christmas", null, null, null, null );
		InsertNewStat( "jul", "xmas", null, null, null, null );
		InsertNewStat( "jul", "x-mas", null, null, null, null );
		
		//negledesign
		InsertNewStat( "top coat", "top coat", "Negledesign", null, null, null );
		InsertNewStat( "moteriktig", "soak off", "Negledesign", null, null, null );
		InsertNewStat( "UV gel", "uv gel", "Negledesign", null, null, null );
		InsertNewStat( "falske negler", "false nails", "Negledesign", "Falske Negler", null, null );
		InsertNewStat( "neglelakk", "nail polish", "Negledesign", "Neglelakk", null, null );
		InsertNewStat( "neglelakk", "nail enamel", "Negledesign", "Neglelakk", null, null );
		InsertNewStat( "t&aringnegler", "toe nails", "Negledesign", "T&aringnegler", null, null );
		InsertNewStat( "negledesign", "nail art", "Negledesign", null, null, null );
		InsertNewStat( "manikyr", "manicure", "Negledesign", null, null, null );
		InsertNewStat( "neglestell", "nail care", "Negledesign", null, null, null );
		InsertNewStat( "neglefil", "nail file", "Negledesign", null, null, null );
		
		//dyr
		InsertNewStat( "dyr", "animal", null, null, null, null );
		InsertNewStat( "insekt", "bug", null, null, null, "dyr" );
		InsertNewStat( "slange", "snake", null, null, null, "dyr" );
		InsertNewStat( "geit", "goat", null, null, null, "dyr" );
		InsertNewStat( "kanin", "rabbit", null, null, null, "dyr" );
		InsertNewStat( "egg", "egg", null, null, null, null );
		InsertNewStat( "dinosaur", "dinosaur", null, null, null, "dyr" );
		InsertNewStat( "tyrannosaurus", "tyrannosaurus", null, null, null, "dinosaur" );
		InsertNewStat( "elefant", "elephant", null, null, null, "dyr" );
		InsertNewStat( "ugle", "owl", null, null, null, "dyr" );
		InsertNewStat( "p&aringfugl", "peacock", null, null, null, "dyr" );
		InsertNewStat( "svane", "swan", null, null, null, "dyr" );
		InsertNewStat( "sommerfugl", "butterfly", null, null, null, "dyr" );
		InsertNewStat( "katt", "cat", null, null, null, "dyr" );
		InsertNewStat( "skorpion", "scorpion", null, null, null, "dyr" );
		InsertNewStat( "kj&aeligledyr", "pet", null, null, null, "dyr" );
		InsertNewStat( "fisk", "fish", null, null, null, "dyr" );
		InsertNewStat( "&oslashyenstikker", "dragonfly", null, null, null, "dyr" );
		InsertNewStat( "Bambi", "Bambi", null, null, null, "dyr" );
		InsertNewStat( "papeg&oslashye", "parrot", null, null, null, "dyr" );
		InsertNewStat( "fugl", "bird", null, null, null, "dyr" );
		InsertNewStat( "hest", "horse", null, null, null, "dyr" );
		InsertNewStat( "panda", "panda", null, null, null, "dyr" );
		InsertNewStat( "drage", "dragon", null, null, null, null );
		InsertNewStat( "hai", "shark", null, null, null, "dyr" );
		InsertNewStat( "blekksprut", "octopus", null, null, null, "dyr" );
		InsertNewStat( "edderkopp", "spider", null, null, null, "dyr" );
		InsertNewStat( "larve", "caterpillar", null, null, null, "dyr" );
		InsertNewStat( "krokodille", "crocodile", null, null, null, "dyr" );
		InsertNewStat( "sau", "sheep", null, null, null, "dyr" );
		
		//tog
		InsertNewStat( "tog", "train", null, null, "Miniatyrskala - Tog", null );
		InsertNewStat( "lokomotiv", "locomotive", null, null, null, "tog" );
		InsertNewStat( "damplokomotiv", "dampflokomotive", "Modellfigurer", "Miniatyrskala - Tog", "Miniatyrskala - Tog", "tog" );
		InsertNewStat( "kriegslokomotive", "kriegslokomotive", "Modellfigurer", "Miniatyrskala - Tog", "Miniatyrskala - Tog", "tog" );
		InsertNewStat( "BR86", "br86", "Modellfigurer", "Miniatyrskala - Tog", "Miniatyrskala - Tog", "tog" );
		InsertNewStat( "BR 52", "br52", "Modellfigurer", "Miniatyrskala - Tog", "Miniatyrskala - Tog", "tog" );
		InsertNewStat( "BR 52", "br 52", "Modellfigurer", "Miniatyrskala - Tog", "Miniatyrskala - Tog", "tog" );
		InsertNewStat( "modelltog", "train model", "Modellfigurer", null, "Miniatyrskala - Tog", "tog" );
		InsertNewStat( "modelltog", "tran model", "Modellfigurer", null, "Miniatyrskala - Tog", "tog" );
		InsertNewStat( "modelltog", "model train", "Modellfigurer", null, "Miniatyrskala - Tog", "tog" );
		InsertNewStat( "WR360 C12", "wr360 c12 locomotive", "Modellfigurer", null, "Miniatyrskala - Tog", "tog" );
		
		//landskap/scenery
		InsertNewStat( "landskap", "landscape", null, null, "Miniatyrskala - Landskap", null );
		InsertNewStat( "scenery", "scenery", null, null, "Miniatyrskala - Landskap", null );
		InsertNewStat( "planter", null, null, null, "Miniatyrskala - Landskap", null );
		InsertNewStat( "blomst", "flower", null, null, "Miniatyrskala - Landskap", "planter" );
		InsertNewStat( "rose", "rose", null, null, "Miniatyrskala - Landskap", "planter" );
		InsertNewStat( "l&oslashv", "leaf", null, null, "Miniatyrskala - Landskap", "planter" );
		InsertNewStat( "l&oslashv", "leaves", null, null, "Miniatyrskala - Landskap", "planter" );
		InsertNewStat( "tre", "tree", null, null, "Miniatyrskala - Landskap", "planter" );
		InsertNewStat( "tre", "model tree", "Modellfigurer", null, "Miniatyrskala - Landskap", "planter" );
		InsertNewStat( "tre", "tree model", "Modellfigurer", null, "Miniatyrskala - Landskap", "planter" );
		InsertNewStat( "tre", "scale tree", "Modellfigurer", null, "Miniatyrskala - Landskap", "planter" );
		InsertNewStat( "bj&oslashrk", "birch", "Modellfigurer", null, "Miniatyrskala - Landskap", "tre" );
		InsertNewStat( "sand", "sand", null, null, "Miniatyrskala - Landskap", null );
		InsertNewStat( "park", "park", null, null, "Miniatyrskala - Landskap", "landskap" );
		InsertNewStat( "benk", "benk", null, null, "Miniatyrskala - Landskap", "landskap" );
		InsertNewStat( "port", "gate", null, null, "Miniatyrskala - Landskap", null );
		InsertNewStat( "gjerde", "fence", null, null, "Miniatyrskala - Landskap", null );
		InsertNewStat( "lampe", "model lamp", "Modellfigurer", null, "Miniatyrskala - Landskap", "lys" );
		InsertNewStat( "lampe", "lamp model", "Modellfigurer", null, "Miniatyrskala - Landskap", "lys" );
		InsertNewStat( null, "o scale", "Modellfigurer", null, "Miniatyrskala - Landskap", null );
		InsertNewStat( null, "model layout", "Modellfigurer", null, "Miniatyrskala - Landskap", null );
		InsertNewStat( "mennesker", "train people", "Modellfigurer", null, "Miniatyrskala - Landskap", null );
		InsertNewStat( "gress", "grass", "Modellfigurer", "Miniatyrskala - Landskap", "Miniatyrskala - Landskap", "landskap" );
		InsertNewStat( "landskap", "landscape", "Modellfigurer", null, "Miniatyrskala - Landskap", "landskap" );
		InsertNewStat( "palmetre", "palm tree", "Modellfigurer", "Miniatyrskala - Landskap", null, "tre" );
		InsertNewStat( "grantre", "pine tree", "Modellfigurer", "Miniatyrskala - Landskap", null, "tre" );
		InsertNewStat( "vegetasjon", "foliage", null, null, "Miniatyrskala - Landskap", null );
		InsertNewStat( "miniatyrlandskap", "train layout", "Modellfigurer", "Miniatyrskala - Landskap", "Miniatyrskala - Landskap", null );
		InsertNewStat( "miniatyrlandskap", "tran layout", "Modellfigurer", "Miniatyrskala - Landskap", "Miniatyrskala - Landskap", null );
		
		//helikoptere
		InsertNewStat( "helikopter", "helicopter", null, null, "Miniatyrskala - Helikoptere", null );
		InsertNewStat( "Apache", "apache", null, null, "Miniatyrskala - Helikoptere", "helikopter" );
		InsertNewStat( "Black Hawk", "Black Hawk", null, null, "Miniatyrskala - Helikoptere", "helikopter" );
		InsertNewStat( "Cobra", "cobra", null, null, "Miniatyrskala - Helikoptere", null );
		InsertNewStat( "AH-1F", "ah 1f", null, null, "Miniatyrskala - Helikoptere", "helikopter" );
		InsertNewStat( "AH-1S", "ah 1s", null, null, "Miniatyrskala - Helikoptere", "helikopter" );
		InsertNewStat( "AH-64D", "ah 64d", null, null, "Miniatyrskala - Helikoptere", "helikopter" );
		InsertNewStat( "AH-64A", "ah 64a", null, null, "Miniatyrskala - Helikoptere", "helikopter" );
		InsertNewStat( "Sea King", "sea king", null, null, "Miniatyrskala - Helikoptere", "helikopter" );
		InsertNewStat( "Rescue Hawk", "rescue hawk", null, null, "Miniatyrskala - Helikoptere", "helikopter" );
		InsertNewStat( "Firehawk", "firehawk", null, null, "Miniatyrskala - Helikoptere", "helikopter" );
		InsertNewStat( "UH-60A", "uh 60a", null, null, "Miniatyrskala - Helikoptere", "helikopter" );
		InsertNewStat( "HH-60H", "hh-60h", null, null, "Miniatyrskala - Helikoptere", "helikopter" );
		InsertNewStat( "Jayhawk", "jayhawk", null, null, "Miniatyrskala - Helikoptere", "helikopter" );
		InsertNewStat( "HH-60J", "hh 60j", null, null, "Miniatyrskala - Helikoptere", "helikopter" );
		InsertNewStat( "HH-60J", "hh-60j", null, null, "Miniatyrskala - Helikoptere", "helikopter" );
		InsertNewStat( "Mi-24V Hind-E", "mi 24v hind e", null, null, "Miniatyrskala - Helikoptere", "helikopter" );
		
		//miniatyrskala
		InsertNewStat( "slott", "castle", null, null, "Miniatyrskala - Arkitektur", null );
		InsertNewStat( "palass", "palace", null, null, "Miniatyrskala - Arkitektur", null );
		InsertNewStat( "bil", "car", null, null, "Miniatyrskala - Kj&oslashret&oslashyer", null );
		InsertNewStat( "villa", "villa", null, null, "Miniatyrskala - Arkitektur", "hus" );
		InsertNewStat( "hus", "house", null, null, "Miniatyrskala - Arkitektur", null );
		InsertNewStat( "miniatyrhus", "model house", null, null, "Miniatyrskala - Arkitektur", null );
		InsertNewStat( "hytte", "cabin", null, null, "Miniatyrskala - Arkitektur", null );
		InsertNewStat( "skala", "scale", null, null, null, "miniatyr" );
		InsertNewStat( "miniatyrmodell", "sand table model", "Modellfigurer", null, null, "figur" );
		InsertNewStat( "table top", "sand table", "Modellfigurer", null, null, "miniatyrmodell" );
		
		//motorsykler
		InsertNewStat( "motorsykkel", "motorbike", null, null, "Miniatyrskala - Motorsykler", null );
		InsertNewStat( "motorsykkel", "motercycle", null, null, "Miniatyrskala - Motorsykler", null );
		InsertNewStat( "motorsykkel", "motorcycle", null, null, "Miniatyrskala - Motorsykler", null );
		InsertNewStat( "motorsykkel, Harley Davidson, ", "harley davidson", null, null, "Miniatyrskala - Motorsykler", null );
		InsertNewStat( "motorsykkel", "motobike", null, null, "Miniatyrskala - Motorsykler", null );
		
		//modellfigurer
		InsertNewStat( "kriger", "warrior", "Modellfigurer", null, null, null );
		InsertNewStat( "Saracen", "saracen", "Modellfigurer", null, null, null );
		InsertNewStat( "Sorceror", "sorceror", "Modellfigurer", null, null, null );
		InsertNewStat( "Warlock", "warlock", "Modellfigurer", null, null, null );
		InsertNewStat( "kombinering", "combination", null, null, null, null );
		InsertNewStat( "modellsett", "model kit", "Modellfigurer", null, null, null );
		InsertNewStat( "Flakvierling", "flakvierling", "Modellfigurer", null, null, "Tyskland" );
		InsertNewStat( "Mustang", "mustang", "Modellfigurer", null, null, null );
		InsertNewStat( "Flakpanzer", "flakpanzer", "Modellfigurer", null, null, "Tyskland" );
		InsertNewStat( "Suzuki", "suzuki", "Modellfigurer", null, null, null );
		InsertNewStat( "Honda", "honda", "Modellfigurer", null, null, null );
		InsertNewStat( "soldatfigur", "soldier model", "Modellfigurer", null, null, "soldat" );
		//InsertNewStat( "general", "general", "Hobby", "Modellfigurer", null, null );//proccer på generelt
		InsertNewStat( "Kavaleri", "cavalry", "Modellfigurer", null, null, "krig" );
		InsertNewStat( "Dark Elf", "Dark Elf", "Modellfigurer", null, null, "fantasy" );
		InsertNewStat( "Dark Elf", "Dark elves", "Modellfigurer", null, null, "fantasy" );
		InsertNewStat( "High Elf", "High Elf", "Modellfigurer", null, null, "fantasy" );;
		InsertNewStat( "High Elf", "high elves", "Modellfigurer", null, null, "fantasy" );
		InsertNewStat( "Wood Elf", "Wood Elf", "Modellfigurer", null, null, "fantasy" );
		InsertNewStat( "Wood Elf", "Wood elves", "Modellfigurer", null, null, "fantasy" );
		InsertNewStat( "Chaos Dwarf", "chaos dwarf", "Modellfigurer", null, null, "fantasy" );
		InsertNewStat( "Chaos Dwarf", "Chaos Dwarves", "Modellfigurer", null, null, "fantasy" );
		InsertNewStat( "Night Train", "Night Train", "Modellfigurer", "Miniatyrskala - Motorsykler", null, "motorsykkel" );
		InsertNewStat( "sorcerer", "sorcerer", "Modellfigurer", null, null, "fantasy" );
		InsertNewStat( "valkyrie", "valkyrie", "Modellfigurer", null, null , null );
		InsertNewStat( "Sky Talon", "Sky Talon", "Modellfigurer", null, null, null );;
		InsertNewStat( "World of Warcraft", "World of Warcraft", "Modellfigurer", "World of Warcraft", null, "spill" );
		InsertNewStat( "soldat", "soldier", "Modellfigurer", null, null, "krig" );
		InsertNewStat( "1968", "1968", "Modellfigurer", null, null, null );
		InsertNewStat( "Ramses", "Ramses", "Modellfigurer", null, null, "egypt" );
		InsertNewStat( "Napoleonic", "napoleonic", "Modellfigurer", "Miniatyrskala - Napoleonic", null, "krig" );
		InsertNewStat( "hussar", "hussar", "Modellfigurer", null, null, "krig" );
		InsertNewStat( "fantasy", "fantasy", "Modellfigurer", null, null, null );
		InsertNewStat( "samurai", "samurai", "Modellfigurer", null, null, "Japan" );
		InsertNewStat( "Tower Bridge", "Tower Bridge", "Modellfigurer", null, null, "England" );
		InsertNewStat( "warlord", "warlord", "Modellfigurer", null, null, null );
		InsertNewStat( "Grenadier Squad", "Grenadier Squad", "Modellfigurer", null, null, null );
		InsertNewStat( "Blast Shield", "blast shield", "Modellfigurer", null, null, "deler" );
		InsertNewStat( "Shield Base", "shield base", "Modellfigurer", null, null, "deler" );
		InsertNewStat( "Gun Shield", "gun shield", "Modellfigurer", null, null, "deler" );
		InsertNewStat( "skjold", "shield", "Modellfigurer", null, null, null );
		InsertNewStat( "Kommandos", "Kommandos", "Modellfigurer", null, null, null );
		InsertNewStat( "romersk", "roman", "Modellfigurer", null, null, null );
		InsertNewStat( "Halley", "halley", "Modellfigurer", null, null, "motorsykkel" );
		InsertNewStat( "Caesar", "Caesar", "Modellfigurer", null, null, "romersk" );
		InsertNewStat( "kommand&oslashr", "Commander", "Modellfigurer", null, null, null );
		InsertNewStat( "Heavy Artillery", "Heavy Artillery", "Modellfigurer", null, null, "krig" );
		InsertNewStat( "Eiffelt&aringrnet", "eiffel tower", "Modellfigurer", null, null, "Frankrike" );
		InsertNewStat( "minerydding", "mine clearing", null, null, null, null );
		InsertNewStat( "modellfigur", "resin kit", "Modellfigurer", null, null, null );
		InsertNewStat( "modellfigur", "resin kits", "Modellfigurer", null, null, null );

		//leker
		InsertNewStat( "leke", "toy", null, null, null, null );
		InsertNewStat( "dukkehus", "dollhouse", "Leker", null, null, null );
		InsertNewStat( "puslespill", "puzzle", "Leker", null, null, null );
		InsertNewStat( "Babyleke", "baby toy", "Leker", "Babyleker", null, "baby" );
		InsertNewStat( "Barneleke", "kids toy", "Leker", "Barneleker", null, "barn" );
		InsertNewStat( "Barneleke", "children toy", "Leker", "Barneleker", null, "barn" );
		InsertNewStat( "Pet Shop", "Pet Shop", "Modellfigurer", null, null, "leke" );
		InsertNewStat( "lego", "legoland", "Leker", null, null, "leke" );
		InsertNewStat( "lego", "lego", "Leker", "Lego", null, "leke" );
		InsertNewStat( "lego", "legao", "Leker", "Lego", null, "leke" );
		InsertNewStat( "lego", "lubanjiang", "Leker", "Lego", null, "leke" );
		InsertNewStat( "lego", "banbao", "Leker", "Lego", null, "leke" );
		InsertNewStat( "lego", "wange", "Leker", "Lego", null, "leke" );
		InsertNewStat( "Lego", "ninjago", "Leker", "Lego", null, "leke" );
		InsertNewStat( "puttekasse", "shape box", "Leker", "Babyleker", null, "baby" );
		InsertNewStat( "treleke", "wooden toy", "Leker", null, null, null );
		InsertNewStat( "lego", "sluban", "Leker", "Lego", null, "leke" );
		InsertNewStat( "lego", "luban", "Leker", "Lego", null, "leke" );
		InsertNewStat( "ballong", "balloon", "Leker", "Ballonger", null, "fest" );
		InsertNewStat( "Rasleleke", "sand hammer", "Leker", null, null, "baby" );
		InsertNewStat( "Thomastoget", "thomastoget", "Leker", null, null, null );
		InsertNewStat( null, "educational toy", "Leker", null, null, null );
		InsertNewStat( "byggeklosser", "building block", "Leker", "Byggeklosser", null, null );
		InsertNewStat( "byggeklosser", "building brick", "Leker", "Byggeklosser", null, null );
		InsertNewStat( "Gundam", "gundam", "Leker", "Gundam", "Gundam", "robot" );
		InsertNewStat( "klosser", "blocks", "Leker", null, null, null );
		InsertNewStat( "Spacerail", "spacerail", "Leker", null, null, null );
		InsertNewStat( "Spacerail", "space rail", "Leker", null, null, null );
		InsertNewStat( "Dukke", "doll", "Leker", "Dukker", null, null );
		InsertNewStat( "soldrevet leke", "solar toy", "Leker", null, null, null );
		InsertNewStat( "stifter", "mushroom nail", "Leker", null, null, null );
		InsertNewStat( "baby", "early learning", "Leker", null, null, null );
		InsertNewStat( null, "fisher price", "Leker", null, null, null );
		InsertNewStat( "baby", "toddler", "Leker", "Babyleker", null, null );
		InsertNewStat( "baby", "infant", "Leker", "Babyleker", null, null );
		InsertNewStat( "baby", "baby", null, null, null, null ); //for 2-ordskriterie
		InsertNewStat( "barn", "kid", null, null, null, null ); //for 2-ordskriterie
		
		//2.verdenskrig
		InsertNewStat( "2.verdenskrig", "world war ii", "Modellfigurer", "Miniatyrskala - WW2", "Miniatyrskala - WW2", null );
		InsertNewStat( "2.verdenskrig", "wwii", "Modellfigurer", "Miniatyrskala - WW2", "Miniatyrskala - WW2", null );
		InsertNewStat( "2.verdenskrig", "ww2", "Modellfigurer", "Miniatyrskala - WW2", "Miniatyrskala - WW2", null );
		InsertNewStat( "2.verdenskrig", "ww ii", "Modellfigurer", "Miniatyrskala - WW2", "Miniatyrskala - WW2", null );
		InsertNewStat( "1941", "1942", "Modellfigurer", null, "Miniatyrskala - WW2", null );
		InsertNewStat( "1942", "1942", "Modellfigurer", null, "Miniatyrskala - WW2", null );
		InsertNewStat( "1943", "1943", "Modellfigurer", null, "Miniatyrskala - WW2", null );
		InsertNewStat( "1944", "1944", "Modellfigurer", null, "Miniatyrskala - WW2", null );
		InsertNewStat( "1945", "1945", "Modellfigurer", null, "Miniatyrskala - WW2", null );
		InsertNewStat( "1946", "1946", "Modellfigurer", null, "Miniatyrskala - WW2", null );
		InsertNewStat( "leopard", "leopard", null, null, "Miniatyrskala - WW2", null );
		InsertNewStat( "Hochkiss", "Hochkiss", "Modellfigurer", "Miniatyrskala - WW2", "Miniatyrskala - WW2", null );
		InsertNewStat( "Richelieu", "richelieu", "Modellfigurer", "Miniatyrskala - WW2", "Miniatyrskala - WW2", "b&aringt" );
		InsertNewStat( "Theus Willys", "theus willys", "Modellfigurer", "Miniatyrskala - WW2", "Miniatyrskala - WW2", null );
		InsertNewStat( "Hitler", "hitler", "Modellfigurer", "Miniatyrskala - WW2", "Miniatyrskala - WW2", "Tyskland" );
		InsertNewStat( "RF-8", "rf 8", null, null, "Miniatyrskala - WW2", "kj&oslashret&oslashy" );
		InsertNewStat( "Aerosani", "aerosani", null, null, "Miniatyrskala - WW2", "kj&oslashret&oslashy" );
		InsertNewStat( "Aerosani", "aerosan", null, null, "Miniatyrskala - WW2", "kj&oslashret&oslashy" );

		//tanks
		InsertNewStat( "Dragon 7278", "dragon 7278", "Modellfigurer", "Miniatyrskala - WW2", "Miniatyrskala - WW2", "tanks" );
		InsertNewStat( "tanks", "tank", null, null, "Miniatyrskala - Tanks", "krig" );
		InsertNewStat( "Kingtiger", "Kingtiger", "Modellfigurer", "Miniatyrskala - WW2", "Miniatyrskala - WW2", "tanks" );
		InsertNewStat( "t-34", "t 34", "Modellfigurer", "Miniatyrskala - WW2", "Miniatyrskala - WW2", "tanks" );
		InsertNewStat( "t-34", "t-34", "Modellfigurer", "Miniatyrskala - WW2", "Miniatyrskala - WW2", "tanks" );
		InsertNewStat( "Jagdpanther", "jagdpanther", "Modellfigurer", "Miniatyrskala - WW2", "Miniatyrskala - WW2", "tanks" );
		InsertNewStat( "brummbaer", "brummbar", "Modellfigurer", "Miniatyrskala - WW2", "Miniatyrskala - WW2", "tanks" );
		InsertNewStat( "Sturm Tiger", "sturmtiger", "Modellfigurer", "Miniatyrskala - WW2", "Miniatyrskala - WW2", "tanks" );
		InsertNewStat( "Sturm Tiger", "sturm tiger", "Modellfigurer", "Miniatyrskala - WW2", "Miniatyrskala - WW2", "tanks" );
		InsertNewStat( "Stug", "stug", "Modellfigurer", "Miniatyrskala - WW2", "Miniatyrskala - WW2", "tanks" );
		InsertNewStat( "panzerjager", "panzerjager", "Modellfigurer", "Miniatyrskala - WW2", "Miniatyrskala - WW2", "tanks" );
		InsertNewStat( "Tank Destroyer", "tank destroyer", "Modellfigurer", null, null, "tanks" );
		InsertNewStat( "Centauro", "centauro", "Modellfigurer", null, null, "tanks" );
		InsertNewStat( "AAVP-7A1 RAM/RS", "aavp 7a1 ram/rs", "Modellfigurer", null, null, "tanks" );
		InsertNewStat( "AAVP-7A1 RAM/RS", "aavp-7a1 ram/rs", "Modellfigurer", null, null, "tanks" );
		InsertNewStat( "Pz.Kpfw", "pz.kpfw", "Modellfigurer", null, null, "tanks" );
		InsertNewStat( "KV-1", "kv 1", "Modellfigurer", null, null, "tanks" );
		InsertNewStat( "STRV 103B MBT", "strv 103b mbt", "Modellfigurer", null, null, "tanks" );
		InsertNewStat( "T-55", "t 55", "Modellfigurer", null, null, "tanks" );
		InsertNewStat( "Sherman", "sherman", "Modellfigurer", null, null, "tanks" );
		InsertNewStat( "Ariete MBT", "ariete mbt", "Modellfigurer", null, null, "tanks" );
		InsertNewStat( "Ariete", "ariete", "Modellfigurer", null, null, "tanks" );
		
		//skip og marine
		InsertNewStat( "marine", "navy", null, null, null, null );
		InsertNewStat( "marine", "marine", null, null, null, null );
		InsertNewStat( "marinekorps", "marine corps", "Modellfigurer", null, null, "marine" );
		InsertNewStat( "skip", "ship", null, null, "Miniatyrskala - Marine", "marine" );
		InsertNewStat( "armada", "armada", null, null, "Miniatyrskala - Marine", "marine" );
		InsertNewStat( "seilb&aringt", "sailboat", null, null, "Miniatyrskala - Marine", "marine" );
		InsertNewStat( "b&aringt", "boat", null, null, "Miniatyrskala - Marine", "marine" );
		InsertNewStat( "USS Arizona", "uss arizona", "Modellfigurer", "Miniatyrskala - WW2", "Miniatyrskala - WW2", "krigsskip" );
		InsertNewStat( "Prinz Eugen", "prinz eugen", "Modellfigurer", "Miniatyrskala - WW2", "Miniatyrskala - WW2", "krigsskip" );
		InsertNewStat( "USS Princeton", "uss princeton", "Modellfigurer", null, null, "krigsskip" );
		InsertNewStat( "USS Arthur W. Radford", "uss arthur w. radford", "Modellfigurer", null, null, "krigsskip" );
		InsertNewStat( "USS Harry", "uss harry", "Modellfigurer", null, null, "krigsskip" );
		InsertNewStat( "USS Spruance", "uss spruance", "Modellfigurer", null, null, "krigsskip" );
		InsertNewStat( "USS Astoria", "uss astoria", "Modellfigurer", null, null, "krigsskip" );
		InsertNewStat( "USS Ticonderoga", "uss ticonderoga", "Modellfigurer", null, null, "krigsskip" );
		InsertNewStat( "USS Vincennes", "uss vincennes", "Modellfigurer", null, null, "krigsskip" );
		InsertNewStat( "USS Kidd", "uss kidd", "Modellfigurer", null, null, "krigsskip" );
		InsertNewStat( "USS Enterprise", "uss enterprise", "Modellfigurer", null, null, "krigsskip" );
		InsertNewStat( "USS Harry W. Hill", "uss harry w. hill", "Modellfigurer", null, null, "krigsskip" );
		InsertNewStat( "USS Los Angeles", "uss los angeles", "Modellfigurer", null, null, "krigsskip" );
		InsertNewStat( "USS SSN-21 Seawolf", "uss ssn 21 seawolf", "Modellfigurer", null, null, "krigsskip" );
		InsertNewStat( "USS SSN-21 Seawolf", "uss ssn-21 seawolf", "Modellfigurer", null, null, "krigsskip" );
		InsertNewStat( "USS Nimitz", "uss nimitz", "Modellfigurer", null, null, "krigsskip" );
		InsertNewStat( "USS San Francisco", "uss san francisco", "Modellfigurer", "Miniatyrskala - WW2", "Miniatyrskala - WW2", "1942" );
		InsertNewStat( "USS San Orleans", "uss san orleans", "Modellfigurer", "Miniatyrskala - WW2", "Miniatyrskala - WW2", "1942" );
		InsertNewStat( "HMS Renown", "hms renown", "Modellfigurer", "Miniatyrskala - WW2", "Miniatyrskala - WW2", "1945" );
		InsertNewStat( "USS Baltimore", "uss baltimore", "Modellfigurer", "Miniatyrskala - WW2", "Miniatyrskala - WW2", "1943" );
		InsertNewStat( "HMS Zulu", "hms zulu", "Modellfigurer", null, null, "krigsskip" );
		InsertNewStat( "hangarskip", "aircraft carrier", null, null, null, "krigsskip" );
		InsertNewStat( "sj&oslashr&oslashver", "pirate", null, null, null, "marine" );
		InsertNewStat( "krigsskip", "warship", null, null, "Miniatyrskala - Marine", "skip" );
		InsertNewStat( "krigsskip", "war ship", null, null, "Miniatyrskala - Marine", "skip" );
		InsertNewStat( "krigsskip", "battleship", null, null, "Miniatyrskala - Marine", "skip" );
		InsertNewStat( "destroyer", "destroyer", null, null, null, "krigsskip" );
		InsertNewStat( "zerztorer", "zerztorer", "Modellfigurer", null, null, "krigsskip" );
		InsertNewStat( "battlecruiser", "battlecruiser", null, null, null, "skip" );
		InsertNewStat( "cruiser", "cruiser", null, null, null, null );
		InsertNewStat( "passasjerskip", "passenger ship", null, null, "Miniatyrskala - Marine", "skip" );
		InsertNewStat( "dampskip", "steamship", null, null, "Miniatyrskala - Marine", "skip" );
		InsertNewStat( "Titanic", "titanic", null, null, "Miniatyrskala - Marine", "passasjerskip" );
		InsertNewStat( "Bismarck", "bismarck", "Modellfigurer", "Miniatyrskala - WW2", "Miniatyrskala - WW2", "krigsskip" );
		InsertNewStat( "kj&oslashret&oslashytransport", "vehicle landing", null, null, null, "krigsskip" );
		InsertNewStat( "kj&oslashret&oslashytransport", "landing craft", null, null, null, "krigsskip" );
		InsertNewStat( "XXIII", "german type xxiii", null, null, null, "krigsskip" );
		InsertNewStat( "IX-C", "type ix c", null, null, null, "krigsskip" );
		InsertNewStat( "u-b&aringt", "u boat", null, null, null, "krigsskip" );
		InsertNewStat( "u-b&aringt", "submarine", null, null, null, "krigsskip" );
		InsertNewStat( "u-b&aringt", "u boote", null, null, null, "krigsskip" );
		InsertNewStat( "CA-32", "ca 32", null, null, "Miniatyrskala - WW2", "krigsskip" );
		InsertNewStat( "CA-68", "ca 68", null, null, "Miniatyrskala - WW2", "krigsskip" );
		InsertNewStat( "Z-25", "z 25", null, null, "Miniatyrskala - WW2", "krigsskip" );
		InsertNewStat( "Z-28", "z 28", null, null, "Miniatyrskala - WW2", "krigsskip" );
		InsertNewStat( "Z-43", "z 43", null, null, null, "krigsskip" );
		InsertNewStat( "Varyag", "varyag", null, null, null, "krigsskip" );
		InsertNewStat( "RN-Roma", "rn roma", null, null, null, "krigsskip" );
		InsertNewStat( "Tirpitz", "tirpitz", null, null, "Miniatyrskala - WW2", "krigsskip" );
		
		//fly
		InsertNewStat( "fly", "aircraft", null, null, "Miniatyrskala - Fly", null );
		InsertNewStat( "fly", "airplane", null, null, "Miniatyrskala - Fly", null );
		InsertNewStat( "fly", "plane", null, null, "Miniatyrskala - Fly", null );
		InsertNewStat( "flymodell", "airplane model", "Modellfigurer", "Miniatyrskala - Fly", "Miniatyrskala - Fly", null );
		InsertNewStat( "passasjerfly", "air bus", null, null, "Miniatyrskala - Fly", "fly" );
		InsertNewStat( "sj&oslashfly", "seaplane", null, null, "Miniatyrskala - Fly", "fly" );
		InsertNewStat( "stealth fighter", "stealth fighter", null, null, "Miniatyrskala - Fly", "fly" );
		InsertNewStat( "Nighthawk", "nighthawk", null, null, "Miniatyrskala - Fly", "fly" );
		InsertNewStat( "fighter", "fighter", null, null, "Miniatyrskala - Fly", "fly" );
		InsertNewStat( "Strike Flanker", "strike flanker", null, null, "Miniatyrskala - Fly", "fly" );
		InsertNewStat( "SU-30", "su 30", null, null, "Miniatyrskala - Fly", "fly" );
		InsertNewStat( "SU-34", "su 34", null, null, "Miniatyrskala - Fly", "fly" );
		InsertNewStat( "SU-34", "su-34", null, null, "Miniatyrskala - Fly", "fly" );
		InsertNewStat( "Vigilante", "vigilante", null, null, "Miniatyrskala - Fly", "fly" );
		InsertNewStat( "BF 109E", "bf 109e", "Modellfigurer", "Miniatyrskala - WW2", "Miniatyrskala - WW2", "fly" );
		InsertNewStat( "jaguar", "jaguar", null, null, "Miniatyrskala - Fly", null );
		InsertNewStat( "PLAAF", "plaaf", null, null, "Miniatyrskala - Fly", null );
		InsertNewStat( "Berkut", "berkut", null, null, "Miniatyrskala - Fly", "fly" );
		InsertNewStat( "Tomcat", "tomcat", null, null, "Miniatyrskala - Fly", "fly" );
		InsertNewStat( "Flanker G", "flanker g", null, null, "Miniatyrskala - Fly", "fly" );
		InsertNewStat( "C-48C", "c 48c", null, null, "Miniatyrskala - Fly", "fly" );
		InsertNewStat( "MiG-29M", "mig 29m", null, null, "Miniatyrskala - Fly", "fly" );
		InsertNewStat( "Skytrain", "skytrain", null, null, "Miniatyrskala - Fly", "fly" );
		InsertNewStat( "Spiteful", "spiteful", null, null, "Miniatyrskala - Fly", "fly" );
		InsertNewStat( "Rafale B", "rafale b", null, null, "Miniatyrskala - Fly", "fly" );
		InsertNewStat( "Boeing 777", "b777", null, null, "Miniatyrskala - Fly", "fly" );
		InsertNewStat( "Harbin H-5", "harbin h 5", null, null, "Miniatyrskala - Fly", "fly" );
		
		//kjøretøyer
		InsertNewStat( "kj&oslashret&oslashy", "vehicle", null, null, "Miniatyrskala - Kj&oslashret&oslashyer", null );
		InsertNewStat( "bil", "car", null, null, null, "kj&oslashret&oslashy" );
		InsertNewStat( "Dragon 6381", "dragon 6381", "Modellfigurer", null, null, "kj&oslashret&oslashy" );
		InsertNewStat( "buss", "bus", null, null, null, "kj&oslashret&oslashy" );
		InsertNewStat( "brannkj&oslashret&oslashy", "fire engine", null, null, null, "kj&oslashret&oslashy" );
		InsertNewStat( "truck", "truck", null, null, null, "kj&oslashret&oslashy" );
		InsertNewStat( "racerkj&oslashret&oslashy", "formula car", null, null, null, "kj&oslashret&oslashy" );
		InsertNewStat( "bulldoser", "bulldozer", null, null, null, "kj&oslashret&oslashy" );
		InsertNewStat( "lastekj&oslashret&oslashy", "freight", null, null, null, "kj&oslashret&oslashy" );
		InsertNewStat( "Mortar Carrier", "mortar carrier", null, null, null, "kj&oslashret&oslashy" );
		InsertNewStat( "Jeep", "jeep", null, null, null, "kj&oslashret&oslashy" );
		InsertNewStat( "Dingo mk", "dingo mk", null, null, null, "kj&oslashret&oslashy" );
		InsertNewStat( "transporttrailer", "transport trailer", null, null, null, "kj&oslashret&oslashy" );
		InsertNewStat( null, "scania", null, null, null, "kj&oslashret&oslashy" );
		InsertNewStat( "recon vehicle", "scout car", "Modellfigurer", null, null, "kj&oslashret&oslashy" );
		InsertNewStat( "pansret bil", "armoured car", "Modellfigurer", null, null, "kj&oslashret&oslashy" );
		InsertNewStat( "pansret bil", "armored car", "Modellfigurer", null, null, "kj&oslashret&oslashy" );
		InsertNewStat( "Pickup", "pickup", null, null, null, "kj&oslashret&oslashy" );
		InsertNewStat( "M706", "m706", null, null, null, "kj&oslashret&oslashy" );
		InsertNewStat( "M113A3", "m113a3", null, null, null, "kj&oslashret&oslashy" );
		InsertNewStat( "M113A3", "m 113a3", null, null, null, "kj&oslashret&oslashy" );
		InsertNewStat( "M113 ACAV", "m 113acav", null, null, null, "kj&oslashret&oslashy" );
		
		//WH40k
		InsertNewStat( "WH40k", "WH40k", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", null );
		InsertNewStat( "Blood Angels", "blood angels", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Angel Belial", "angel belial", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "engel", "angel", null, null, "Warhammer 40k", null );
		InsertNewStat( "Chaplain", "chaplain", null, null, "Warhammer 40k", null );
		InsertNewStat( "Chaos Space Marines", "Chaos Space Marines", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Tau, Piranha", "Tau Piranha", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Tau", "Tau", "Modellfigurer", "Warhammer 40k", null, "WH40k" );
		InsertNewStat( "Necron", "Necron", "Modellfigurer", "Warhammer 40k", null, "WH40k" );
		InsertNewStat( "Imperial Guard", "Imperial Guard", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Dark Eldar", "Dark Eldar", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );;
		InsertNewStat( "Eldar", "Eldar", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "space marine", "space marine", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "terminator", "terminator", "Modellfigurer", null, "Warhammer 40k", null );
		InsertNewStat( "Piranha Squad", "Piranha Squad", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Canoptek Wraiths", "canoptek wraiths", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Exemplar", "Exemplar", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Space Wolves", "space wolves", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Grey Knight", "grey knight", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Skullcrushers of Khorne", "Skullcrushers of Khorne", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Lord on Juggernaut", "Lord on Juggernaut", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Lord Commissar", "Lord Commissar", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Lord of Slaanesh", "Lord of Slaanesh", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "ork", "ork", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Warbikes", "Warbikes", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Lugft Huron, Chapter Master of the Astral Claws", "lugft huron chapter master of the astral claws", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Chapter Master", "chapter master", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Iron Priest", "iron priest", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Mangler Squigs", "mangler squigs", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Drop Pod", "Drop Pod", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Typhus", "Typhus", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Elysian", "Elysian", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Heavy Bolter", "heavy bolter", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Bolter", "Bolter", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Drop Troops", "Drop Troop", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Drazhoath", "Drazhoath", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Heldrake", "Heldrake", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Daemon Prince", "Daemon Prince", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Daemon", "Daemon", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Plague Drone", "plague drone", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Champion of Tzeentch", "Champion of Tzeentch", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Tyranids", "Tyranid", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Lictor", "Lictor", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Canis Wolfborn", "Canis Wolfborn", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Mk III Iron Armour", "Mk III Iron Armour", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "runde baser", "round base", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Arco Flagellants", "Arco Flagellants", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Inquisitor", "Inquisitor", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Sslyth", "Sslyth", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Death Korps of Krieg", "death korps of krieg", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Death Korps of Krieg", "dkk", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Herald of Tzeentch", "Herald of Tzeentch", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Plague Ogryn Leader", "Plague Ogryn Leader", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Lietpold the Black", "Lietpold the Black", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Ironsides Handgunner", "Ironsides Handgunner", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Sergeant Kell", "Sergeant Kell", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Caradryan", "Caradryan", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Death Jester", "death jester", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Captain Lysander", "Captain Lysander", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Lysander", "Lysander", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Commander Shadowsun", "Commander Shadowsun", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Shadowsun", "Shadowsun", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Champion", "Champion", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Master of Signal", "Master of Signal", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Sabre Defence Platform", "Sabre Defence Platform", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Lascannon", "Lascannon", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Ultramarine", "Ultramarine", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Venerable Dreadnought", "Venerable Dreadnought", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "World Eaters", "World Eaters", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "conversion", "conversion", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Death Guard", "Death Guard", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Artillery Crew,", "Artillery Crew,", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Renegade", "Renegade", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Apostate Preachers of Nurgle", "Apostate Preachers of Nurgle", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Ogryn Berserker", "Ogryn Berserker", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Rogue Psykers", "Rogue Psykers", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Irillyth, Phoenix Lord of the Shadow Spectres", "irillyth phoenix lord of the shadow spectres", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Blood Slaughterer Impaler", "Blood Slaughterer Impaler", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Special Weapon", "Special Weapon", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Tauros Venator", "Tauros Venator", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Colossal Squig", "Colossal Squig", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Drop Sentinel", "Drop Sentinel", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Heavy Support", "Heavy Support", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Obliterators", "Obliterators", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Scyla Anfingrimm", "Scyla Anfingrimm", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Swooping Hawk", "Swooping Hawk", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Forgefiend", "Forgefiend", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Maulerfiend", "Maulerfiend", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Soul Grinder", "soul grinder", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Carriage with Earthshaker Cannon", "Carriage with Earthshaker Cannon", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Kill Krusha Tank", "kill krusha tank", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Ahriman", "ahriman", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Njal Stormcaller", "njal stormcaller", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Nurgle", "nurgle", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Harlequin", "harlequin", null, null, "Warhammer 40k", null );
		InsertNewStat( "Phoenix Lord", "phoenix lord", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Jain Zar", "jain zar", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Illuminor Szeras", "illuminor szeras", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Thunderwolf", "thunderwolf", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Hive Tyrant", "hive tyrant", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Venomthrope", "venomthrope", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Pyrovore", "pyrovore", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Deathleaper", "deathleaper", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Old One Eye", "old one eye", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Razorwing", "razorwing", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Ur Ghul", "ur ghul", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Killkannon", "killkannon", "Modellfigurer", "Warhammer 40k", "Warhammer 40k", "WH40k" );
		InsertNewStat( "Sun Shark Bomber", "sun shark bomber", "Modellfigurer", null, "Warhammer 40k", "WH40k" );
		InsertNewStat( "Ashaki", "ashaki", "Modellfigurer", null, "Warhammer 40k", "WH40k" );
		InsertNewStat( "Reaver Titan", "reaver titan", "Modellfigurer", null, "Warhammer 40k", "WH40k" );
		InsertNewStat( "Tech Marine", "techmarine", "Modellfigurer", null, "Warhammer 40k", "WH40k" );
		InsertNewStat( "Autarch", "autarch", "Modellfigurer", null, "Warhammer 40k", "WH40k" );
		InsertNewStat( "power weapon", "power weapon", "Modellfigurer", null, "Warhammer 40k", "WH40k" );
		InsertNewStat( "Asterion Moloc", "asterion moloc", "Modellfigurer", null, "Warhammer 40k", "WH40k" );
		InsertNewStat( "Ivanus Enkomi of the Minotaurs", "ivanus enkomi of the minotaurs", "Modellfigurer", null, "Warhammer 40k", "WH40k" );
		InsertNewStat( "Raven Guard", "raven guard", "Modellfigurer", null, "Warhammer 40k", "WH40k" );
		InsertNewStat( "Shadow Captain", "Shadow Captain", "Modellfigurer", null, "Warhammer 40k", "WH40k" );
		InsertNewStat( "Korvydae", "korvydae", "Modellfigurer", null, "Warhammer 40k", "WH40k" );
		InsertNewStat( "Huron Blackheart", "huron blackheart", "Modellfigurer", null, "Warhammer 40k", "WH40k" );
		InsertNewStat( "jump pack", "jump pack", "Modellfigurer", null, "Warhammer 40k", "WH40k" );
		InsertNewStat( "Farseer", "farseer", "Modellfigurer", null, "Warhammer 40k", "WH40k" );
		InsertNewStat( "Great Brass Scorpion", "great brass scorpion", "Modellfigurer", null, "Warhammer 40k", "WH40k" );	
		InsertNewStat( "Astorath the Grim", "astorath the grim", "Modellfigurer", null, "Warhammer 40k", "WH40k" );
		InsertNewStat( "Lukas the Trickster", "lukas the trickster", "Modellfigurer", null, "Warhammer 40k", "WH40k" );
		InsertNewStat( "Company Master", "company master", "Modellfigurer", null, "Warhammer 40k", "WH40k" );
		InsertNewStat( "Missile Squad", "missile squad", "Modellfigurer", null, "Warhammer 40k", "WH40k" );
		InsertNewStat( "Rune Priest", "rune priest", "Modellfigurer", null, "Warhammer 40k", "WH40k" );
		InsertNewStat( "Dark Reapers", "dark reapers", "Modellfigurer", null, "Warhammer 40k", "WH40k" );
		InsertNewStat( "Karandras", "karandras", "Modellfigurer", null, "Warhammer 40k", "WH40k" );
		InsertNewStat( "Dreadnought", "dreadnought", "Modellfigurer", null, "Warhammer 40k", "WH40k" );
		InsertNewStat( "Sonic Dreadnought", "sonic dreadnought", "Modellfigurer", null, "Warhammer 40k", "WH40k" );
		InsertNewStat( "Emperor's Children", "emperor's children", "Modellfigurer", null, "Warhammer 40k", "WH40k" );
		InsertNewStat( "Canoptek Spyder", "canoptek spyder", "Modellfigurer", null, "Warhammer 40k", "WH40k" );
		InsertNewStat( "Blood Slaughterer", "blood slaughterer", "Modellfigurer", null, "Warhammer 40k", "WH40k" );
		InsertNewStat( "Bloodthirster", "bloodthirster", "Modellfigurer", null, "Warhammer 40k", "WH40k" );
		InsertNewStat( "Greater Daemon of Khorne", "greater daemon of khorne", "Modellfigurer", null, "Warhammer 40k", "WH40k" );
		
		//WHFB
		InsertNewStat( "WHFB", null, "Modellfigurer", "Warhammer Fantasy", "Warhammer Fantasy", null );
		InsertNewStat( "Dragon Ogres", "dragon ogre", null, null, "Warhammer Fantasy", "WHFB" );
		InsertNewStat( "Warriors of Chaos", "warriors of chaos", "Modellfigurer", "Warhammer Fantasy", "Warhammer Fantasy", "WHFB" );
		InsertNewStat( "Celestial Hurricanum", "Celestial Hurricanum", "Modellfigurer", "Warhammer Fantasy", "Warhammer Fantasy", "WHFB" );
		InsertNewStat( "Loremaster", "Loremaster", "Modellfigurer", "Warhammer Fantasy", "Warhammer Fantasy", "WHFB" );
		InsertNewStat( "Lothern Skycutter", "lothern skycutter", "Modellfigurer", "Warhammer Fantasy", "Warhammer Fantasy", "WHFB" );
		InsertNewStat( "Drazhar", "Drazhar", "Modellfigurer", "Warhammer Fantasy", "Warhammer Fantasy", "WHFB" );
		InsertNewStat( "Alith Anar the Shadow King", "alith anar, the shadow kin", "Modellfigurer", "Warhammer Fantasy", "Warhammer Fantasy", "WHFB" );
		InsertNewStat( "Vampire Counts", "Vampire Counts", "Modellfigurer", "Warhammer Fantasy", "Warhammer Fantasy", "WHFB" );
		InsertNewStat( "Skeleton Warriors", "Skeleton Warriors", "Modellfigurer", "Warhammer Fantasy", "Warhammer Fantasy", "WHFB" );
		InsertNewStat( "Helblaster Volley Gun", "Helblaster Volley Gun", "Modellfigurer", "Warhammer Fantasy", "Warhammer Fantasy", "WHFB" );
		InsertNewStat( "Helstorm Rocket Battery", "Helstorm Rocket Battery", "Modellfigurer", "Warhammer Fantasy", "Warhammer Fantasy", "WHFB" );
		InsertNewStat( "Chosen Command", "Chosen Command", "Modellfigurer", "Warhammer Fantasy", "Warhammer Fantasy", "WHFB" );
		InsertNewStat( "Skaven", "Skaven", "Modellfigurer", "Warhammer Fantasy", "Warhammer Fantasy", "WHFB" );
		InsertNewStat( "Warlord on Brood Horror", "Warlord on Brood Horror", "Modellfigurer", "Warhammer Fantasy", "Warhammer Fantasy", "WHFB" );
		InsertNewStat( "Prince Althran", "Prince Althran", "Modellfigurer", "Warhammer Fantasy", "Warhammer Fantasy", "WHFB" );
		InsertNewStat( "Festus", "Festus", "Modellfigurer", "Warhammer Fantasy", "Warhammer Fantasy", "WHFB" );
		InsertNewStat( "Handmaiden of the Everqueen", "handmaiden of the everqueen", "Modellfigurer", "Warhammer Fantasy", "Warhammer Fantasy", "WHFB" );
		InsertNewStat( "Shadow Warriors", "Shadow Warriors", "Modellfigurer", "Warhammer Fantasy", "Warhammer Fantasy", "WHFB" );
		InsertNewStat( "Azhag", "Azhag", "Modellfigurer", "Warhammer Fantasy", "Warhammer Fantasy", "WHFB" );
		InsertNewStat( "Flamespyre Phoenix", "Flamespyre Phoenix", "Modellfigurer", "Warhammer Fantasy", "Warhammer Fantasy", "WHFB" );
		InsertNewStat( "Goblin Wolf Chariot", "Goblin Wolf Chariot", "Modellfigurer", "Warhammer Fantasy", "Warhammer Fantasy", "WHFB" );
		InsertNewStat( "Orcs and Goblins", "Orcs and Goblins", "Modellfigurer", "Warhammer Fantasy", "Warhammer Fantasy", "WHFB" );
		InsertNewStat( "Goblin", "Goblin", "Modellfigurer", "Warhammer Fantasy", "Warhammer Fantasy", "WHFB" );
		InsertNewStat( "Orc", "Orc", "Modellfigurer", "Warhammer Fantasy", "Warhammer Fantasy", "WHFB" );
		InsertNewStat( "Tyrion", "Tyrion", "Modellfigurer", "Warhammer Fantasy", "Warhammer Fantasy", "WHFB" );
		InsertNewStat( "Loremaster of Hoeth", "Loremaster of Hoeth", "Modellfigurer", "Warhammer Fantasy", "Warhammer Fantasy", "WHFB" );
		InsertNewStat( "Korhil", "Korhil", "Modellfigurer", "Warhammer Fantasy", "Warhammer Fantasy", "WHFB" );
		InsertNewStat( "Archaon the everchosen", "Archaon the everchosen", "Modellfigurer", "Warhammer Fantasy", "Warhammer Fantasy", "WHFB" );
		InsertNewStat( "Archaon", "Archaon", "Modellfigurer", "Warhammer Fantasy", "Warhammer Fantasy", "WHFB" );
		InsertNewStat( "Alarielle the Radiant", "alarielle the radiant", "Modellfigurer", "Warhammer Fantasy", "Warhammer Fantasy", "WHFB" );
		InsertNewStat( "Bale Taurus", "Bale Taurus", "Modellfigurer", "Warhammer Fantasy", "Warhammer Fantasy", "WHFB" );
		InsertNewStat( "Theodore Bruckner and Reaper", "Theodore Bruckner and Reaper", "Modellfigurer", "Warhammer Fantasy", "Warhammer Fantasy", "WHFB" );
		InsertNewStat( "Sigvald the Magnificent", "Sigvald the Magnificent", "Modellfigurer", "Warhammer Fantasy", "Warhammer Fantasy", "WHFB" );
		InsertNewStat( "Chrace", "chracian", "Modellfigurer", "Warhammer Fantasy", "Warhammer Fantasy", "WHFB" );
		InsertNewStat( "Blood Throne of Khorne", "Blood Throne of Khorne", "Modellfigurer", "Warhammer Fantasy", "Warhammer Fantasy", "WHFB" );
		InsertNewStat( "Vilitch the Curseling", "vilitch the curseling", "Modellfigurer", "Warhammer Fantasy", "Warhammer Fantasy", "WHFB" );
		InsertNewStat( "Champion of Khorne", "champion of khorne", "Modellfigurer", null, "Warhammer Fantasy", "WHFB" );
		InsertNewStat( "Champions of Chaos", "champions of chaos", "Modellfigurer", null, "Warhammer Fantasy", "WHFB" );
		InsertNewStat( "Crom the Conquerer", "crom the conquerer", "Modellfigurer", null, "Warhammer Fantasy", "WHFB" );
		InsertNewStat( "Marauder Champion", "marauder champion", "Modellfigurer", "Warhammer Fantasy", "Warhammer Fantasy", "WHFB" );
		InsertNewStat( "Warp Lightning Cannon", "warp lightning cannon", "Modellfigurer", "Warhammer Fantasy", "Warhammer Fantasy", "WHFB" );
		InsertNewStat( "Plagueclaw Catapult", "plagueclaw catapult", "Modellfigurer", "Warhammer Fantasy", "Warhammer Fantasy", "WHFB" );
		InsertNewStat( "Exalted Hero of Chaos", "exalted hero of chaos", "Modellfigurer", "Warhammer Fantasy", "Warhammer Fantasy", "WHFB" );
		
		//warhammer bitz
		InsertNewStat( "bitz", "bitz", "Modellfigurer", "Warhammer Bitz", "Warhammer Bitz", "Warhammer" );
		InsertNewStat( "Bolter", "bolter", null, "Warhammer", null, "bitz" );
		InsertNewStat( "Umbra Ferrox", "umbra ferrox", null, "Warhammer", null, "bitz" );
		InsertNewStat( "Umbra Ferrox", "umbra ferro", null, "Warhammer", null, "bitz" );
		InsertNewStat( "Heavy Bolter set", "heavy bolter set", "Modellfigurer", null, null, "bitz" );
		InsertNewStat( "Weapon set", "weapon set", "Modellfigurer", null, null, "bitz" );
		InsertNewStat( "Weapons set", "weapons set", "Modellfigurer", null, null, "bitz" );
		InsertNewStat( "Weapons set", "weapons pack", "Modellfigurer", null, null, "bitz" );
		InsertNewStat( "Phobos Pattern", "Phobos Pattern", "Modellfigurer", null, null, "bitz" );
		InsertNewStat( "Umbra Pattern", "umbra Pattern", "Modellfigurer", null, null, "bitz" );
		InsertNewStat( "Bolt Pistols", "Bolt Pistols", "Modellfigurer", null, null, "bitz" );
		InsertNewStat( "Power Fist Set", "power fist set", "Modellfigurer", "Warhammer Bitz", "Warhammer Bitz", "bitz" );
		InsertNewStat( "Oppgraderingspakke", "upgrade pack", "Modellfigurer", "Warhammer Bitz", "Warhammer Bitz", "bitz" );
		InsertNewStat( "Oppgraderingspakke", "upgrade set", "Modellfigurer", "Warhammer Bitz", "Warhammer Bitz", "bitz" );
		InsertNewStat( "Autocannon set", "autocannon set", "Modellfigurer", "Warhammer Bitz", "Warhammer Bitz", "bitz" );
		InsertNewStat( "Boneswords set", "boneswords set", "Modellfigurer", "Warhammer Bitz", "Warhammer Bitz", "bitz" );
		InsertNewStat( "chainfist", "chainfist", "Modellfigurer", "Warhammer Bitz", "Warhammer Bitz", "bitz" );
		
		//div warhammer
		InsertNewStat( "40k", "40k", "Modellfigurer", null, null, "Warhammer" );
		InsertNewStat( "40k", "40'000", "Modellfigurer", null, null, "Warhammer" );
		InsertNewStat( "Warhammer", "the hammer of war", "Modellfigurer", null, null, "miniatyr" );
		InsertNewStat( null, "warhammer", "Modellfigurer", null, null, "Warhammer" );
		InsertNewStat( "Khorne", "Khorne", "Modellfigurer", null, null, "Warhammer" );
		
		//produsenter
		InsertNewStat( null, "swarovski", null, null, null, "rhinestones" );
		InsertNewStat( null, "fimo", null, null, null, "modelleringsleire" );
		InsertNewStat( null, "plasticine", null, null, null, "modelleringsleire" );
		InsertNewStat( null, "play doh", null, null, null, "modelleringsleire" );
		InsertNewStat( null, "rigant", "Smykker", null, null, null );
		InsertNewStat( null, "italina", "Smykker", null, null, null );
		InsertNewStat( null, "dingya", "Smykker", null, null, null );
		InsertNewStat( null, "hasbro", "Leker", null, null, null );
		InsertNewStat( null, "forge world", "Modellfigurer", null, null, "Warhammer" );
		InsertNewStat( null, "games workshop", "Modellfigurer", null, null, null );
		InsertNewStat( null, "hobby boss", "Modellfigurer", null, null, null );
		InsertNewStat( null, "hobbyboss", "Modellfigurer", null, null, null );
		InsertNewStat( null, "trumpeter", "Modellfigurer", null, null, null );
		InsertNewStat( null, "griffon model", "Modellfigurer", null, null, null );
		InsertNewStat( null, "griffonmodel", "Modellfigurer", null, null, null );
		InsertNewStat( null, "bronco", "Modellfigurer", null, null, null );
		InsertNewStat( null, "tamiya", "Modellfigurer", null, null, null );
		InsertNewStat( null, "evolution miniatures", "Modellfigurer", null, null, null );
		InsertNewStat( null, "caesar miniatures", "Modellfigurer", null, null, null );
		InsertNewStat( null, "scania", "Modellfigurer", "Miniatyrskala - Biler", null, "kj&oslashret&oslashy" );
		InsertNewStat( null, "etmodel", "Modellfigurer", null, null, null );
		InsertNewStat( null, "zvezda", "Modellfigurer", null, null, "1/72" );

		/*if ( Parser.InneholderSeparertOrd( "stellux", AllTexts ) > -1) { Produsent = Produsent + "Stellux "; }
		if ( Parser.InneholderSeparertOrd( "kitty hawk", AllTexts ) > -1) { Produsent = Produsent + "Kitty Hawk "; }
		if ( Parser.InneholderSeparertOrd( "meng", AllTexts ) > -1) { Produsent = Produsent + "Meng "; }
		if ( Parser.InneholderSeparertOrd( "afv club", AllTexts ) > -1) { Produsent = Produsent + "AFV Club "; }
		*/
	}
	
	private void InsertNewStat( String Egennavn_Norsk, String Egennavn_Engelsk, String Hovedkategori, String Subkategori, String Kategori_Modellfigurer, String Generalisering ) {
		if ( Egennavn_Engelsk != null ) {
			Egennavn_Engelsk = Egennavn_Engelsk.toLowerCase();
		}
		for ( int X = 0 ; X <  Temaer.length ; X++ ) {
			if ( Temaer[X] == null ) {
				Temaer[X] = new Object_ItemStats_Tema( Egennavn_Norsk, Egennavn_Engelsk, Hovedkategori, Subkategori, Kategori_Modellfigurer, Generalisering );
				return;
			}
		}
		System.err.println( "ItemStats_Tema har ikke plass til alle temaer!" );
	}
	
	public Object_ItemStats_Tema[] HentListe_Objekter() {
		return Temaer;
	}
	
}
